branches: folders

pipeline:  
  hubpublish:
    image: plugins/docker
    settings:
      repo: servercentral/elastalert
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      build_args:
        - ELASTALERT_VERSION=master
    secrets: [ docker_username, docker_password ]
    environment:
      - ELASTALERT_VERSION=master
    when:
      branch: folders

  deployment:
    image: registry.servercentral.com/drone-plugins/awxdeployment
    pull: true
    environment:
      - PROJECT_PLAYBOOK=playbooks/elasticsearch/elasticsearch.yml
    volumes:
      - /etc/tower/tower_cli.cfg:/etc/tower/tower_cli.cfg
    when:
      event: push
      branch: folders 
      status: success
